#!/usr/bin/perl -Ilib/
#
#  Trivial Redis-server in Perl, which proxies to SQLite.
#
# Steve
# --
#

use strict;
use warnings;

use Predis;
use Backend::SQLite;


#
#  The backend storage module.
#
my $backend = Backend::SQLite->new( file => "/tmp/lost.db" );

my $server = Predis->new( backend => $backend );
$server->serve();
